name: Laravel CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: dom, curl, mbstring, pdo, sqlite, pdo_sqlite

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-interaction --no-progress
        cp .env.example .env
        php artisan key:generate

    - name: Build application
      run: |
        # Aquí puedes agregar comandos específicos de build si los tienes
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

  test:
    runs-on: ubuntu-latest
    needs: build  # Esta línea asegura que la etapa de pruebas solo se ejecute después de build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: dom, curl, mbstring, pdo, sqlite, pdo_sqlite

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-interaction --no-progress
        cp .env.example .env
        php artisan key:generate

    - name: Run tests
      run: php artisan test
